services:
  postgres:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_USER: ministryhub
      POSTGRES_PASSWORD: ministryhub
      POSTGRES_DB: ministryhub_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
